# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hybridgroup-serialport"
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guillaume Pierronnet", "Alan Stern", "Daniel E. Shipton", "Tobin Richard", "Hector Parra", "Ryan C. Payne", "Adrian Zankich", "Ron Evans"]
  s.date = "2013-01-14"
  s.description = "Ruby/SerialPort is a Ruby library that provides a class for using RS-232 serial ports."
  s.email = "serialport@hybridgroup.com"
  s.extensions = ["ext/native/extconf.rb", "ext/native/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "CHECKLIST",
    "LICENSE",
    "MANIFEST",
    "README",
    "Rakefile",
    "VERSION",
    "ext/native/extconf.rb",
    "ext/native/posix_serialport_impl.c",
    "ext/native/serialport.c",
    "ext/native/serialport.h",
    "ext/native/win_serialport_impl.c",
    "hybridgroup-serialport.gemspec",
    "lib/oscheck.rb",
    "lib/serialport.rb",
    "test/miniterm.rb",
    "test/set_readtimeout.rb"
  ]
  s.homepage = "http://github.com/hybridgroup/ruby-serialport/"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Library for using RS-232 serial ports."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

