# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monoxit-serialport}
  s.version = "1.2.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guillaume Pierronnet", "Alan Stern", "Daniel E. Shipton", "Tobin Richard", "Hector Parra", "Ryan C. Payne", "Adrian Zankich", "Ron Evans", "Masami Yamakawa"]
  s.date = %q{2013-11-17}
  s.description = %q{Ruby/SerialPort is a Ruby library that provides a class for using RS-232 serial ports.}
  s.email = %q{myamakawa@monoxit.com}
  s.extensions = ["ext/native/extconf.rb", "ext/native/extconf.rb"]
  s.extra_rdoc_files = [
    "CHANGELOG",
    "LICENSE",
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "CHECKLIST",
    "LICENSE",
    "MANIFEST",
    "README",
    "Rakefile",
    "VERSION",
    "ext/native/extconf.rb",
    "ext/native/posix_serialport_impl.c",
    "ext/native/serialport.c",
    "ext/native/serialport.h",
    "ext/native/win_serialport_impl.c",
    "lib/oscheck.rb",
    "lib/serialport.rb",
    "monoxit-serialport.gemspec",
    "test/miniterm.rb",
    "test/set_readtimeout.rb"
  ]
  s.homepage = %q{http://github.com/MONOXIT/ruby-serialport/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Library for using RS-232 serial ports.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

